/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PedidoDao;
import controller.ProdutoDao;
import controller.UsuarioDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import model.enums.TipoProduto;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.plaf.basic.BasicScrollBarUI;
import model.ItemProduto;
import model.Pedido;
import model.enums.TipoPedido;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author pedro
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {

    PedidoDao pedidoDao = new PedidoDao();
    List<ItemProduto> carrinho = new ArrayList<>();
    JLabel exibir = new javax.swing.JLabel();
    JLabel labelProduto = new JLabel();

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();
        pedidoDao.ciarTabelaPedido();
        atualizarProdutoPainel(carrinho);
        atualizarAcompanhamento();
        atualizarBebida();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        tab1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tab2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tab3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tab4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnSair = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jp1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        precoField = new javax.swing.JTextField();
        descField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        fotoField = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        tipoProduto = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jp4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        atualizarBtn = new javax.swing.JButton();
        deletarBtn = new javax.swing.JButton();
        searchedPreco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        searchedName = new javax.swing.JTextField();
        searchId = new javax.swing.JTextField();
        searchedDescricao = new javax.swing.JTextField();
        procurarBtn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        procurarBtn1 = new javax.swing.JLabel();
        procurarBtn2 = new javax.swing.JLabel();
        procurarBtn3 = new javax.swing.JLabel();

        jPanel12.setBackground(new java.awt.Color(238, 238, 238));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkout (1).png"))); // NOI18N
        jLabel35.setText("Nº do Pedido");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dollar (2) (1).png"))); // NOI18N
        jLabel48.setText("Total");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/processing-time (1).png"))); // NOI18N
        jLabel49.setText("Status do Pedido");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jLabel48)
                .addGap(83, 83, 83)
                .addComponent(jLabel49)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(238, 238, 238));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkout (1).png"))); // NOI18N
        jLabel32.setText("Nº do Pedido");

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dollar (2) (1).png"))); // NOI18N
        jLabel46.setText("Total");

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/processing-time (1).png"))); // NOI18N
        jLabel47.setText("Status do Pedido");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jLabel46)
                .addGap(83, 83, 83)
                .addComponent(jLabel47)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(128, 0, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        tab1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab1.setForeground(new java.awt.Color(0, 0, 0));
        tab1.setText("Cadastrar Pedidos");
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab1)
                .addGap(43, 43, 43))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tab2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab2.setForeground(new java.awt.Color(0, 0, 0));
        tab2.setText("Ver Pedidos");
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(tab2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab3.setForeground(new java.awt.Color(0, 0, 0));
        tab3.setText("Cadastrar Produtos");
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab3)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tab4.setForeground(new java.awt.Color(0, 0, 0));
        tab4.setText("Ver Produtos");
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setText("Sair");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White logo - no background (6).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 1100));

        jp1.setBackground(new java.awt.Color(255, 255, 255));
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MY ORDER");
        jp1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 80));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jp1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1019, 14, 31, 30));

        jPanel5.setBackground(new java.awt.Color(238, 238, 238));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Confirm Order");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 540, 216, 38));

        jp1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 220, 590));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jp1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 730, 260));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jp1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 730, 280));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (2).png"))); // NOI18N
        jLabel19.setText("Hambúrgueres");
        jp1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (2).png"))); // NOI18N
        jLabel33.setText("Bebidas");
        jp1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, -1, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star (2).png"))); // NOI18N
        jLabel34.setText("Acompanhamentos");
        jp1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 30));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jp1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 730, 240));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkout (1).png"))); // NOI18N
        jLabel20.setText("Pedido");
        jp1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 100, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Items:");
        jp1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 60, 20));

        getContentPane().add(jp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1050, 1100));

        jp2.setBackground(new java.awt.Color(255, 255, 255));
        jp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ver Pedidos");
        jp2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 0, -1, 95));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jp2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 101, 983, 763));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("X");
        jLabel11.setPreferredSize(new java.awt.Dimension(16, 32));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jp2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1019, 14, 31, 30));

        getContentPane().add(jp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 0, 1050, 1100));

        jp3.setBackground(new java.awt.Color(255, 255, 255));
        jp3.setPreferredSize(new java.awt.Dimension(1331, 1010));
        jp3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Cadastrar Produto");
        jp3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 0, -1, 95));

        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });
        jp3.add(nomeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 122, 210, 38));

        precoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoFieldActionPerformed(evt);
            }
        });
        jp3.add(precoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 210, 210, 40));

        descField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descFieldMouseClicked(evt);
            }
        });
        jp3.add(descField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, 40));

        jLabel2.setText("Descrição");
        jp3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel7.setText("Nome");
        jp3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel8.setText("Preço");
        jp3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jp3.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));
        jp3.add(fotoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 240, 170));

        btnFoto.setText("Carregar Foto");
        btnFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFotoMouseClicked(evt);
            }
        });
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        jp3.add(btnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 240, 60));

        tipoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HAMBURGUER", "ACOMPANHAMENTO", "BEBIDA" }));
        tipoProduto.setToolTipText("");
        tipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoProdutoActionPerformed(evt);
            }
        });
        jp3.add(tipoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 120, 40));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("X");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jp3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1019, 14, 31, 30));

        getContentPane().add(jp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1050, 1100));

        jp4.setBackground(new java.awt.Color(255, 255, 255));
        jp4.setMinimumSize(new java.awt.Dimension(1331, 1010));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ver Produto");

        JTable.setBackground(new java.awt.Color(102, 102, 102));
        JTable.setForeground(new java.awt.Color(255, 255, 255));
        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable.setGridColor(new java.awt.Color(0, 0, 0));
        JTable.setSelectionBackground(new java.awt.Color(128, 0, 0));
        JTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        JTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(JTable);
        if (JTable.getColumnModel().getColumnCount() > 0) {
            JTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            JTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            JTable.getColumnModel().getColumn(2).setPreferredWidth(30);
            JTable.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        atualizarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atualizarBtn.setForeground(new java.awt.Color(0, 0, 0));
        atualizarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh-page-option (1).png"))); // NOI18N
        atualizarBtn.setText("Atualizar");
        atualizarBtn.setBorderPainted(false);
        atualizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarBtnMouseClicked(evt);
            }
        });

        deletarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletarBtn.setForeground(new java.awt.Color(0, 0, 0));
        deletarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-can (1).png"))); // NOI18N
        deletarBtn.setText("Deletar");
        deletarBtn.setBorderPainted(false);
        deletarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletarBtnMouseClicked(evt);
            }
        });
        deletarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBtnActionPerformed(evt);
            }
        });

        searchedPreco.setBackground(new java.awt.Color(102, 102, 102));
        searchedPreco.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Procurar por ID");

        searchedName.setBackground(new java.awt.Color(102, 102, 102));
        searchedName.setForeground(new java.awt.Color(255, 255, 255));

        searchId.setBorder(null);
        searchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIdActionPerformed(evt);
            }
        });

        searchedDescricao.setBackground(new java.awt.Color(102, 102, 102));
        searchedDescricao.setForeground(new java.awt.Color(255, 255, 255));

        procurarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        procurarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procurarBtnMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("_________________________");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("____________");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("X");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Nome");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Preço");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Descrição");

        procurarBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconProduct (2).png"))); // NOI18N
        procurarBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procurarBtn1MouseClicked(evt);
            }
        });

        procurarBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dollar (1).png"))); // NOI18N
        procurarBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procurarBtn2MouseClicked(evt);
            }
        });

        procurarBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checklist (2).png"))); // NOI18N
        procurarBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procurarBtn3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jp4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(852, 852, 852)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jp4Layout.createSequentialGroup()
                                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jp4Layout.createSequentialGroup()
                                        .addComponent(deletarBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(atualizarBtn))
                                    .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jp4Layout.createSequentialGroup()
                                            .addComponent(searchId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(procurarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchedName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jp4Layout.createSequentialGroup()
                                            .addComponent(searchedPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(procurarBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(searchedDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(procurarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(procurarBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(procurarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12)))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(procurarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchedPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(procurarBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchedDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(procurarBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletarBtn)
                            .addComponent(atualizarBtn)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        getContentPane().add(jp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1050, 1100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        TelaLogin tela = new TelaLogin();
        this.setVisible(false);
        tela.setVisible(true);
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked

        PedidoDao pedidoDao = new PedidoDao();
        atualizarProdutoPainel(carrinho);
        atualizarAcompanhamento();
        atualizarBebida();
        System.out.println(carrinho);
    }//GEN-LAST:event_tab1MouseClicked

    private void atualizarProdutoPainel(List<ItemProduto> carrinho) {
        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jPanel8.removeAll();
        jPanel8.revalidate();
        jPanel8.repaint();

        JPanel produtosPanel = new JPanel();
        produtosPanel.setLayout(new BoxLayout(produtosPanel, BoxLayout.X_AXIS)); // Alterado para X_AXIS

        ProdutoDao produtoDao = new ProdutoDao();
        List<Produto> selectHamburgueres = produtoDao.selectHamburgueres();

        for (Produto selectHamburguere : selectHamburgueres) {
            System.out.println(selectHamburguere.getNome());
            JPanel jPanelProduto = new javax.swing.JPanel();
            jPanelProduto.setBackground(new java.awt.Color(255, 255, 255));
            jPanelProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            System.out.println(selectHamburguere.getFoto());
            JLabel foto = new javax.swing.JLabel();

            BufferedImage bufferedImage = null;
            try {
                bufferedImage = ImageIO.read(selectHamburguere.getFoto());
            } catch (IOException ex) {
                Logger.getLogger(TelaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

            foto.setIcon(new ImageIcon(bufferedImage));

            JLabel titulo = new javax.swing.JLabel();
            titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

            titulo.setForeground(new java.awt.Color(0, 0, 0));

            titulo.setText(selectHamburguere.getNome());

            JLabel descricao = new javax.swing.JLabel();
            descricao.setForeground(new java.awt.Color(153, 153, 153));

            descricao.setText(selectHamburguere.getDescricao());

            JLabel preco = new javax.swing.JLabel();
            preco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            preco.setForeground(new java.awt.Color(0, 0, 0));

            preco.setText("R$" + selectHamburguere.getPreco());

            JButton botao = new javax.swing.JButton();
            botao.setBackground(new java.awt.Color(204, 204, 204));
            botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (3).png"))); // NOI18N
            botao.setBorder(null);

            final Produto produtoSelecionado = selectHamburguere;

            botao.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {

                    carrinho.add(new ItemProduto(produtoSelecionado.getNome(), produtoSelecionado.getPreco(), produtoSelecionado.getId()));
                    atualizarCarrinho(evt, carrinho);

                }

            });

            jPanelProduto.add(botao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 30, 30));

            jPanelProduto.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 56, -1));

            jPanelProduto.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, -1, 110));
            jPanelProduto.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, 176, -1));
            jPanelProduto.add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, 176, -1));

            produtosPanel.add(jPanelProduto);

        }

        JScrollPane scrollPane = new JScrollPane(produtosPanel);
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setBorder(null);
        scrollPane.getHorizontalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = Color.BLACK; // Cor do thumb (barra de rolagem)
                this.trackColor = Color.WHITE; // Cor da pista (fundo do scrollbar)
            }
        });
        jPanel8.setLayout(new BorderLayout());
        jPanel8.add(scrollPane, BorderLayout.CENTER);

        jPanel8.revalidate();
        jPanel8.repaint();
    }

    private void atualizarCarrinho(java.awt.event.ActionEvent evt, List<ItemProduto> carrinho) {
        System.out.println("Entrou aqui por aquele motivo");
        exibir.setFont(new java.awt.Font("Segoe UI", 1, 12));
        exibir.setForeground(new java.awt.Color(0, 0, 0));
        exibir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel5.remove(labelProduto);

        // Define a posição Y inicial
        int y = 10;

        System.out.println("Chegou aqui 2");
        for (ItemProduto produto : carrinho) {
            labelProduto = new JLabel(produto.getNome());
            labelProduto.setFont(new java.awt.Font("Segoe UI", 1, 12));
            labelProduto.setForeground(new java.awt.Color(0, 0, 0));
            labelProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            // Adiciona o JLabel ao painel com a posição Y atualizada
            jPanel5.add(labelProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, y, 120, 48));

            // Atualiza a posição Y para o próximo JLabel
            y += 25;
        }

        // Atualiza o painel para refletir as mudanças
        jPanel5.revalidate();
        jPanel5.repaint();
    }

    private void atualizarAcompanhamento() {
        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jPanel9.removeAll();
        jPanel9.revalidate();
        jPanel9.repaint();

        JPanel produtosPanel = new JPanel();
        produtosPanel.setLayout(new BoxLayout(produtosPanel, BoxLayout.X_AXIS)); // Alterado para X_AXIS

        ProdutoDao produtoDao = new ProdutoDao();
        List<Produto> acompanhamentos = produtoDao.selectAcompanhamentos();

        for (Produto acompanhamento : acompanhamentos) {
            JPanel jPanelProduto = new javax.swing.JPanel();
            jPanelProduto.setBackground(new java.awt.Color(255, 255, 255));
            jPanelProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            JLabel foto = new javax.swing.JLabel();

            BufferedImage bufferedImage = null;
            try {
                bufferedImage = ImageIO.read(acompanhamento.getFoto());
            } catch (IOException ex) {
                Logger.getLogger(TelaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

            foto.setIcon(new ImageIcon(bufferedImage));

            JLabel titulo = new javax.swing.JLabel();
            titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

            titulo.setForeground(new java.awt.Color(0, 0, 0));

            titulo.setText(acompanhamento.getNome());

            JLabel descricao = new javax.swing.JLabel();
            descricao.setForeground(new java.awt.Color(153, 153, 153));

            descricao.setText(acompanhamento.getDescricao());

            JLabel preco = new javax.swing.JLabel();
            preco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            preco.setForeground(new java.awt.Color(0, 0, 0));

            preco.setText("R$" + acompanhamento.getPreco());

            JButton botao = new javax.swing.JButton();
            botao.setBackground(new java.awt.Color(204, 204, 204));
            botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (3).png"))); // NOI18N
            botao.setBorder(null);

            final Produto acompanhamentoSelecionado = acompanhamento;

            botao.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    carrinho.add(new ItemProduto(acompanhamentoSelecionado.getNome(), acompanhamentoSelecionado.getPreco(), acompanhamentoSelecionado.getId()));
                    atualizarCarrinho(evt, carrinho);
                }
            });

            jPanelProduto.add(botao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 30, 30));

            jPanelProduto.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 56, -1));

            jPanelProduto.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
            jPanelProduto.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 176, -1));
            jPanelProduto.add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 190, -1));

            produtosPanel.add(jPanelProduto);
        }

        JScrollPane scrollPane = new JScrollPane(produtosPanel);
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setBorder(null);
        scrollPane.getHorizontalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = Color.BLACK; // Cor do thumb (barra de rolagem)
                this.trackColor = Color.WHITE; // Cor da pista (fundo do scrollbar)
            }
        });
        jPanel9.setLayout(new BorderLayout());
        jPanel9.add(scrollPane, BorderLayout.CENTER);

        jPanel9.revalidate();
        jPanel9.repaint();

    }

    private void atualizarBebida() {
        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jPanel11.removeAll();
        jPanel11.revalidate();
        jPanel11.repaint();

        JPanel produtosPanel = new JPanel();
        produtosPanel.setLayout(new BoxLayout(produtosPanel, BoxLayout.X_AXIS)); // Alterado para X_AXIS

        ProdutoDao produtoDao = new ProdutoDao();
        List<Produto> bebidas = produtoDao.selectBebida();

        for (Produto bebida : bebidas) {
            JPanel jPanelProduto = new javax.swing.JPanel();
            jPanelProduto.setBackground(new java.awt.Color(255, 255, 255));
            jPanelProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            JLabel foto = new javax.swing.JLabel();

            BufferedImage bufferedImage = null;
            try {
                bufferedImage = ImageIO.read(bebida.getFoto());
            } catch (IOException ex) {
                Logger.getLogger(TelaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

            foto.setIcon(new ImageIcon(bufferedImage));

            JLabel titulo = new javax.swing.JLabel();
            titulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

            titulo.setForeground(new java.awt.Color(0, 0, 0));

            titulo.setText(bebida.getNome());

            JLabel descricao = new javax.swing.JLabel();
            descricao.setForeground(new java.awt.Color(153, 153, 153));

            descricao.setText(bebida.getDescricao());

            JLabel preco = new javax.swing.JLabel();
            preco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            preco.setForeground(new java.awt.Color(0, 0, 0));

            preco.setText("R$" + bebida.getPreco());

            JButton botao = new javax.swing.JButton();
            botao.setBackground(new java.awt.Color(204, 204, 204));
            botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (3).png"))); // NOI18N
            botao.setBorder(null);

            final Produto bebidaSelecionada = bebida;
            botao.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {

                    carrinho.add(new ItemProduto(bebidaSelecionada.getNome(), bebidaSelecionada.getPreco(), bebidaSelecionada.getId()));
                    atualizarCarrinho(evt, carrinho);
                }
            });

            jPanelProduto.add(botao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 30, 30));

            jPanelProduto.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 56, -1));

            jPanelProduto.add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 174, -1));
            jPanelProduto.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 176, -1));
            jPanelProduto.add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 176, -1));

            produtosPanel.add(jPanelProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
        }

        JScrollPane scrollPane = new JScrollPane(produtosPanel);
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setBorder(null);

        scrollPane.getHorizontalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = Color.BLACK; // Cor do thumb (barra de rolagem)
                this.trackColor = Color.WHITE; // Cor da pista (fundo do scrollbar)
            }
        });

        jPanel11.setLayout(new BorderLayout());
        jPanel11.add(scrollPane, BorderLayout.CENTER);

        jPanel11.revalidate();
        jPanel11.repaint();

    }
    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        selectPedidos();
    }//GEN-LAST:event_tab2MouseClicked

    private void selectPedidos() {
        jp2.setVisible(true);
        jp1.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jPanel14.removeAll();
        jPanel14.revalidate();
        jPanel14.repaint();

        List<Pedido> pedidos = pedidoDao.selectPedidos();
        JPanel produtosPanel = new JPanel();
        produtosPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();

        int col = 0;
        int row = 0;

        for (Pedido pedido : pedidos) {
            JPanel jpanelProduto = new JPanel();
            jpanelProduto.setBackground(new java.awt.Color(238, 238, 238));
            jpanelProduto.setLayout(new BorderLayout()); // Usar BorderLayout para posicionar o botão
            jpanelProduto.setPreferredSize(new Dimension(300, 300)); // Ajuste a largura e altura conforme necessário
            jpanelProduto.setBorder(BorderFactory.createLineBorder(Color.BLACK)); // Adiciona uma borda para separar os painéis

            // Painel interno para conter as labels
            JPanel labelsPanel = new JPanel();
            labelsPanel.setLayout(new BoxLayout(labelsPanel, BoxLayout.Y_AXIS));
            labelsPanel.setBackground(new java.awt.Color(238, 238, 238)); // Mantém o fundo consistente

            JLabel n = new JLabel();
            n.setFont(new java.awt.Font("Segoe UI", 1, 14));
            n.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkout (1).png")));
            n.setText("Nº do Pedido " + pedido.getId());

            JLabel total = new JLabel();
            total.setFont(new java.awt.Font("Segoe UI", 1, 14));
            total.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dollar (2) (1).png")));
            total.setText("Total R$" + pedido.getTotalFromBd());

            JLabel status = new JLabel();
            status.setFont(new java.awt.Font("Segoe UI", 1, 14));
            status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/processing-time (1).png")));
            status.setText("Status: " + pedido.getStatus().toString());

            int espacoVertical = 60; // Espaço vertical em pixels, ajuste conforme necessário

            labelsPanel.add(n);
            labelsPanel.add(Box.createVerticalStrut(espacoVertical));
            labelsPanel.add(total);
            labelsPanel.add(Box.createVerticalStrut(espacoVertical));
            labelsPanel.add(status);

            // Adiciona o painel de labels ao centro do jpanelProduto
            jpanelProduto.add(labelsPanel, BorderLayout.CENTER);

            // Cria e personaliza o JButton
            JButton button = new JButton("Atualizar situacao");
            button.setOpaque(true);
            button.setBorderPainted(false);
            button.setContentAreaFilled(true);
            button.setBackground(Color.WHITE);
            button.setFocusPainted(false); // Remove as linhas de foco

            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Atualiza a situação do pedido
                    pedidoDao.updateSituacao(pedido.getId());

                    // Reexibe a lista de pedidos
                    selectPedidos();
                }
            });

            // Cria e posiciona o JButton na extremidade inferior direita
            JPanel buttonPanel = new JPanel();
            buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));
            buttonPanel.setBackground(new java.awt.Color(238, 238, 238)); // Mantém o fundo consistente
            buttonPanel.add(button);

            jpanelProduto.add(buttonPanel, BorderLayout.SOUTH);

            gbc.gridx = col;
            gbc.gridy = row;
            gbc.insets = new Insets(10, 10, 10, 10); // Espaçamento entre os painéis
            gbc.anchor = GridBagConstraints.FIRST_LINE_START; // Alinha ao topo e início (esquerda)

            produtosPanel.add(jpanelProduto, gbc);

            col++;
            if (col == 3) { // Mudar para a próxima linha após 3 colunas
                col = 0;
                row++;
            }
        }

        JScrollPane jscroll = new JScrollPane(produtosPanel);
        jscroll.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jscroll.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        jscroll.setBorder(null);

        jscroll.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = Color.BLACK; // Cor do thumb (barra de rolagem)
                this.trackColor = Color.WHITE; // Cor da pista (fundo do scrollbar)
            }
        });

        jPanel14.setLayout(new BorderLayout());
        jPanel14.add(jscroll, BorderLayout.CENTER);

        jPanel14.revalidate();
        jPanel14.repaint();
    }


    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        jp3.setVisible(true);
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp4.setVisible(false);

        ProdutoDao produtoDao = new ProdutoDao();
        produtoDao.criarTabela();
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        jp4.setVisible(true);
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);

        ProdutoDao produtoDao = new ProdutoDao();
        List<Produto> produtos = produtoDao.listProduto();

        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nome", "Preço", "Descrição"}, 0);

        JTable.setModel(model);

        for (Produto produto : produtos) {
            model.addRow(new Object[]{produto.getId(), produto.getNome(), produto.getPreco(), produto.getDescricao()});
        }
    }//GEN-LAST:event_tab4MouseClicked

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void precoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoFieldActionPerformed

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked

        String nome = nomeField.getText();
        Double preco = Double.parseDouble(precoField.getText());
        String desc = descField.getText();
        TipoProduto tipo = TipoProduto.valueOf((String) tipoProduto.getSelectedItem());

        FileInputStream file = null;
        try {
            System.out.println(getCaminho());
            file = new FileInputStream(getCaminho());
        } catch (FileNotFoundException ex) {
            System.out.println("O caminho não funcionou!");
        }

        Produto produto = new Produto(nome, preco, desc, tipo, file, 0);
        ProdutoDao produtoDao = new ProdutoDao();

        try {
            produtoDao.adicionarProduto(produto);

            nomeField.setText("");
            precoField.setText("");
            descField.setText("");
            JOptionPane.showMessageDialog(null,
                    "O cadastro ocorreu com sucesso!", "Operação bem sucedida!",
                    JOptionPane.PLAIN_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Não foi possível realizar o cadastro", "Erro de Operação",
                    JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void descFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_descFieldMouseClicked

    private void deletarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletarBtnActionPerformed

    private void searchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchIdActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void procurarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarBtnMouseClicked
        ProdutoDao produtoDao = new ProdutoDao();

        Produto produto = produtoDao.procurarProduto(Integer.parseInt(searchId.getText()));
        if (produto == null) {
            JOptionPane.showMessageDialog(null,
                    "Não existe nenhum produto com esse ID!", "Erro de Operação",
                    JOptionPane.WARNING_MESSAGE);
        }
        searchedName.setText(produto.getNome());
        searchedPreco.setText(String.valueOf(produto.getPreco()));
        searchedDescricao.setText(produto.getDescricao());


    }//GEN-LAST:event_procurarBtnMouseClicked

    private void procurarBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_procurarBtn1MouseClicked

    private void procurarBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarBtn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_procurarBtn2MouseClicked

    private void procurarBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarBtn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_procurarBtn3MouseClicked

    private void atualizarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarBtnMouseClicked
        ProdutoDao produtoDao = new ProdutoDao();
        produtoDao.atualizarProduto(Integer.parseInt(searchId.getText()), searchedName.getText(), Double.parseDouble(searchedPreco.getText()), searchedDescricao.getText());
        tab4MouseClicked(evt);


    }//GEN-LAST:event_atualizarBtnMouseClicked

    private void deletarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletarBtnMouseClicked
        ProdutoDao produtoDao = new ProdutoDao();

        try {
            produtoDao.deletarProduto(Integer.parseInt(searchId.getText()));
            tab4MouseClicked(evt);
            searchId.setText("");
            searchedName.setText("");
            searchedPreco.setText("");
            searchedDescricao.setText("");
            JOptionPane.showMessageDialog(null,
                    "O produto foi deletado com sucesso!", "Operação bem sucedida!",
                    JOptionPane.PLAIN_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Não foi possível remover o produto", "Erro de Operação",
                    JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_deletarBtnMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed

    }//GEN-LAST:event_btnFotoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFotoMouseClicked
        String path = null;
        try {
            JFileChooser filechooser = new JFileChooser();
            FileNameExtensionFilter filter
                    = new FileNameExtensionFilter("image files", "pnj", "jpg", "bmp", "png");
            filechooser.setFileFilter(filter);
            filechooser.setCurrentDirectory(new File("."));
            int result = filechooser.showOpenDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                path = filechooser.getSelectedFile().getAbsolutePath();
                System.out.println(path);
                this.carregar_imagem_autosize(path);
            } else if (result == JFileChooser.CANCEL_OPTION) {
                return;
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnFotoMouseClicked

    private void tipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoProdutoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        Pedido pedido = new Pedido(TipoPedido.ANDAMENTO, carrinho);
        pedidoDao.insertPedido(pedido);

        // Limpa o carrinho
        carrinho.clear();

        // Remove todos os JLabels do painel
        Component[] components = jPanel5.getComponents();
        for (Component component : components) {
            if (component instanceof JLabel) {
                jPanel5.remove(component);
            }
        }

        // Atualiza o painel para refletir as mudanças
        jPanel5.revalidate();
        jPanel5.repaint();

        // Mostra uma mensagem de sucesso
        JOptionPane.showMessageDialog(null, "O pedido foi cadastrado com sucesso!");


    }//GEN-LAST:event_jButton3MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuPrincipal().setVisible(true);
            }
        });
    }

    public void carregar_imagem_autosize(String CaminhoDaImagem) {
        setCaminho(CaminhoDaImagem);
        int lastIndex = CaminhoDaImagem.lastIndexOf("\\") + 1;
        CaminhoDaImagem = CaminhoDaImagem.substring(lastIndex);
        String caminho = "/imagesprodutos/" + CaminhoDaImagem;

        System.out.println("Entrou no método");
        ImageIcon imagem = new ImageIcon(getClass().getResource(caminho));
        System.out.println("Pegou Imagem com sucesso!");
        Image modelImagem = imagem.getImage();
        Image ModelEscalas = modelImagem.getScaledInstance(this.fotoField.getWidth(), this.fotoField.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ImagemAutoSize = new ImageIcon(ModelEscalas);
        System.out.println(ImagemAutoSize);
        this.fotoField.setIcon(ImagemAutoSize);

    }

    public String getCaminho() {
        return caminho;
    }

    public void setCaminho(String caminho) {
        this.caminho = caminho;
    }

    private String caminho;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton atualizarBtn;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnFoto;
    private javax.swing.JLabel btnSair;
    private javax.swing.JButton deletarBtn;
    private javax.swing.JTextField descField;
    private javax.swing.JLabel fotoField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JTextField nomeField;
    private javax.swing.JTextField precoField;
    private javax.swing.JLabel procurarBtn;
    private javax.swing.JLabel procurarBtn1;
    private javax.swing.JLabel procurarBtn2;
    private javax.swing.JLabel procurarBtn3;
    private javax.swing.JTextField searchId;
    private javax.swing.JTextField searchedDescricao;
    private javax.swing.JTextField searchedName;
    private javax.swing.JTextField searchedPreco;
    private javax.swing.JLabel tab1;
    private javax.swing.JLabel tab2;
    private javax.swing.JLabel tab3;
    private javax.swing.JLabel tab4;
    private javax.swing.JComboBox<String> tipoProduto;
    // End of variables declaration//GEN-END:variables
}
